### ISSUE TITLE
Releasing v2.0

### ISSUE THREAD

**Issue by simon3z** [simon3z/image-inspector#18]
@pweil- @enoodle are we good to release v2.0? Anything else?

Please make sure that all your use-cases are working properly (openscap, webdav with/without chroot, multiple dockercfg files, etc.)

Thanks.

**Comment by enoodle** [comment]
All seems good on my end :+1:

**Comment by pweil-** [comment]
No known issues here.  In the next week or so I'd like to have a call and talk about what the road map is for the project. Some things I'd like to discuss:
1.  builds/testing (aka the catch whatever @pweil- screws up before it merges :smile: )
2.  moving this fork back into the openshift repo
3.  how this can integrate into openshift as part of the infrastructure

**Comment by simon3z** [comment]
Released here:

https://github.com/simon3z/image-inspector/releases/tag/v2.0.0
