### ISSUE TITLE
Failing to cleanup target container when an error occurs 

### ISSUE THREAD

**Issue by simon3z** [simon3z/image-inspector#8]
It seems that if an error occurs [between the target container creation and its removal](https://github.com/simon3z/image-inspector/blob/3f0f8dd05d0c0a3651a760a84979c3ef75289348/image-inspector.go#L242-L290) such container is not removed leaving the environment dirty.

We should create a cleanup function that attempts to remove the target container to call in such cases.

cc @pweil- @enoodle (can anyone of you take this?)

**Comment by pweil-** [comment]
do you prefer the removal in a `defer` or both a `defer` and the current code so that it doesn't hang around for the lifetime of the `ListenAndServe`?

**Comment by simon3z** [comment]
@pweil- yeah probably a defer + current code seems the way to go. If an error occurred we should exit with an error.

(PS. if you're handling this you can build on top of the current refactoring PR you have submitted).

**Comment by pweil-** [comment]
:+1: I'll add it
